# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 20:41
from __future__ import unicode_literals

from django.db import migrations, models
import networkapi.features.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Title of the feature', max_length=300)),
                ('description', models.TextField(help_text='Description of the feature', max_length=5000)),
                ('link_label', models.CharField(help_text="Text to show that links to this feature's details page", max_length=300)),
                ('link_url', models.URLField(help_text="Link to this feature's details page", max_length=2048)),
                ('image', models.FileField(help_text='Image representing this feature', max_length=2048, upload_to=networkapi.features.models.get_features_image_upload_path)),
                ('featured', models.BooleanField(default=False, help_text='Do you want to feature this feature?')),
            ],
            options={
                'verbose_name_plural': 'features',
            },
        ),
    ]
