# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 21:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='expires',
            field=models.DateTimeField(blank=True, default=None, help_text='Unpublish this feature after this date and time (UTC). Leave blank to never unpublish', null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='publish_after',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Publish this feature after this date and time (UTC)', null=True),
        ),
    ]
