# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 22:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0003_auto_20170330_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='publish_after',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Publish this feature after this date and time (UTC)'),
        ),
    ]
