# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0004_auto_20170330_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='expires',
            field=models.DateTimeField(blank=True, default=None, help_text='Hide this feature after this date and time (UTC)', null=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='publish_after',
            field=models.DateTimeField(help_text='Make this feature visible only after this date and time (UTC)', null=True),
        ),
    ]
