# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 21:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0005_auto_20170403_1548'),
        ('features', '0005_auto_20170404_2004'),
    ]

    operations = [
    ]
