# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0006_merge_20170405_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='publish_after',
            field=models.DateTimeField(help_text='Make this feature visible only after this date and time (UTC)and time (UTC)', null=True),
        ),
    ]
