version: 1.0.{build}

branches:

  only:

  - appveyor

clone_depth: 1

build: false

environment:
  DEBUG: True
  DJANGO_SECRET_KEY: secret
  DATABASE_URL: postgres://postgres:5432@localhost:5432/networkapi
  USE_S3: False
  CORS_WHITELIST: "*"
  XSS_PROTECTION: True
  CONTENT_TYPE_NO_SNIFF: True
  SET_HSTS: False
  SSL_REDIRECT: False
  X_FRAME_OPTIONS: DENY
  ALLOWED_HOSTS: localhost

  matrix:

    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.13"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6.1"
      PYTHON_ARCH: "32"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %%PYTHON_ARCH"

install:
  - "%PYTHON%/Scripts/pip.exe install -r requirements.txt"

services:
  - postgresql

test_script:
  - "flake8 . --config=./app/tox.ini"
  - "%PYTHON%/python.exe app/manage.py test"

