version: 1.0.{build}

branches:

  only:

  - appveyor

clone_depth: 1

build: false

environment:
  matrix:

    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.13"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6.1"
      PYTHON_ARCH: "32"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %%PYTHON_ARCH"

install:
  - "%PYTHON%/Scripts/pip.exe install -r requirements.txt"

test_script:
  - "flake8 . --config=./app/tox.ini"
  - "%PYTHON%/python.exe app/manage.py test"
