version: "3"

services:
  web:
    tty: true
    stdin_open: true
    build: .
    env_file: env.default
    ports:
      - "5000:5000"
    depends_on:
      - database
    volumes:
      - ./app:/app
    command: bash -c "../prepare_container.sh && python /app/manage.py collectstatic --no-input && python /app/manage.py runserver 0:5000"

  database:
    restart: always
    image: postgres:latest
    volumes:
      - data:/var/lib/postgresql
    ports:
      - "5432:5432"

  data:
    restart: always
    image: busybox
    volumes:
      - data:/var/lib/postgresql
    command: "true"

volumes:
  data:
