# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-28 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import networkapi.milestones.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(help_text='Title of the milestone', max_length=300)),
                ('photo', models.FileField(help_text='Image associated with the milestone', max_length=2048, upload_to=networkapi.milestones.models.get_milestone_photo_upload_path)),
                ('start_date', models.DateField(help_text='Date on which the milestone begins')),
                ('end_date', models.DateField(help_text='Date on which the milestone ends')),
                ('description', models.TextField(help_text='Briefly describe what the milestone is all about')),
            ],
            options={
                'verbose_name_plural': 'milestones',
                'ordering': ('start_date',),
            },
        ),
        migrations.CreateModel(
            name='MilestoneLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Text to describe the milestone link', max_length=300)),
                ('url', models.URLField(help_text='URL link to the milestone', max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='milestone',
            name='link',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='milestones.MilestoneLink'),
        ),
    ]
