# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-27 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import networkapi.opportunities.models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0003_auto_20170321_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='description',
            field=models.TextField(help_text='Description of the opportunity', max_length=5000),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='featured',
            field=models.BooleanField(default=False, help_text='Do you want to feature this opportunity?'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='image',
            field=models.FileField(help_text='Image representing this opportunity', max_length=2048, upload_to=networkapi.opportunities.models.get_opportunities_image_upload_path),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='link_label',
            field=models.CharField(help_text="Text to show that links to this opportunity's details page", max_length=300),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='link_url',
            field=models.URLField(help_text="Link to this opportunity's details page", max_length=2048),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='name',
            field=models.CharField(help_text='Title of the opportunity', max_length=300),
        ),
    ]
