# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 21:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0003_auto_20170321_2058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opportunity',
            options={'verbose_name_plural': 'opportunities'},
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='order',
        ),
    ]
