# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 21:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0004_auto_20170327_2115'),
        ('opportunities', '0004_auto_20170327_1752'),
    ]

    operations = [
    ]
