# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 21:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User profile'},
        ),
    ]
