# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-09 21:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20170508_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbookmark',
            old_name='user',
            new_name='profile',
        ),
    ]
