# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-05 23:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import pulseapi.entries.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('creators', '0001_initial'),
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('content_url', models.URLField()),
                ('description', models.CharField(blank=True, max_length=600)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('get_involved', models.CharField(blank=True, max_length=300)),
                ('get_involved_url', models.URLField(blank=True)),
                ('interest', models.CharField(blank=True, max_length=600)),
                ('featured', models.BooleanField(default=False)),
                ('internal_notes', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, max_length=2048, upload_to=pulseapi.entries.models.entry_thumbnail_path)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_approved', models.BooleanField(default=False, help_text='Should this show up on the site?')),
                ('creators', models.ManyToManyField(blank=True, related_name='entries', to='creators.Creator')),
                ('issues', models.ManyToManyField(blank=True, related_name='entries', to='issues.Issue')),
            ],
            options={
                'verbose_name_plural': 'entries',
            },
        ),
    ]
