# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-29 22:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import pulseapi.entries.models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_auto_20170508_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        )
    ]
