# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-29 22:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import pulseapi.entries.models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0004_auto_20170529_2241'),
    ]

    operations = [
        # Due to how the PR for this migration worked, no data should
        # ever have existed that made use of the is_approved flag,
        # and so nothing should be lost by this operation.
        migrations.RemoveField(
            model_name='entry',
            name='is_approved',
        ),
    ]
