# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-29 22:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import pulseapi.entries.models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0005_remove_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='moderation_state',
            field=models.ForeignKey(default=pulseapi.entries.models.get_default_moderation_state, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='entries.ModerationState'),
        ),
    ]
