# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-04 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0022_merge_20170405_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='interview_url',
            field=models.URLField(blank=True, help_text='Link to interview for featured people', max_length=500, null=True),
        ),
    ]
